# Generated by Django 4.1.3 on 2023-01-04 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoprojectapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='course',
        ),
        migrations.RenameModel(
            old_name='Country',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='country',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='city',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='country',
            new_name='department',
        ),
    ]
